author: vioCode
description: A true & customized RPG experience.
main: co.viocode.mythic.Mythic
name: Mythic
url: http://viocode.co/
version: 0.0.2
commands:
  mythic:
    description: null
    usage: /<command>
  stats:
    description: null
    usage: /<command>
  hp:
    description: null
    usage: /<command>
  mp:
    description: null
    usage: /<command>
permission:
  mythic.stats:
    description: null